// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsnyqfmdgopicmyhbcik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzbnlxZm1kZ29waWNteWhiY2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NDc4NTgsImV4cCI6MjA1NDUyMzg1OH0.0CdNgIVcruXlNe8bjYyUWzdrwAsJOfGHKtOS47XdV64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);